-- Mahadev Decoration / Part 2
-- Run in Supabase SQL editor. Service role key is server-only.
create extension if not exists pgcrypto;
create type public.user_role as enum ('customer','admin','team');
create type public.booking_request_status as enum ('pending_review','approved','rejected');
create type public.booking_status as enum ('inquiry','pending_review','quote_sent','awaiting_customer_approval','advance_pending','confirmed','in_preparation','team_assigned','in_progress','completed','remaining_payment_pending','closed','cancelled');

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, role public.user_role not null default 'customer', display_name text, phone text, whatsapp text, avatar_url text, notification_preferences jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.customers (id uuid primary key default gen_random_uuid(), profile_id uuid unique references public.profiles(id) on delete cascade, total_spending numeric(12,2) not null default 0, events_completed int not null default 0, internal_admin_notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.booking_requests (id uuid primary key default gen_random_uuid(), reference_number text unique not null, customer_id uuid references public.customers(id), event_type text not null, event_date date not null, city text not null, area text not null, address text not null, venue_name text, budget text, custom_budget numeric(12,2), style text[] not null default '{}', guest_count int not null, venue_type text not null, setting text not null, requirements text not null default '', reference_files jsonb not null default '[]'::jsonb, contact_name text not null, contact_phone text not null, contact_whatsapp text, contact_email text, status public.booking_request_status not null default 'pending_review', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.bookings (id uuid primary key default gen_random_uuid(), customer_id uuid references public.customers(id), request_id uuid unique references public.booking_requests(id), event_type text not null, event_date date not null, location jsonb not null default '{}'::jsonb, budget_range text, style text[] not null default '{}', guest_count int, venue_type text, indoor_outdoor text, requirements text, status public.booking_status not null default 'inquiry', total_price numeric(12,2), advance_paid numeric(12,2) not null default 0, remaining_amount numeric(12,2), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.booking_status_history (id uuid primary key default gen_random_uuid(), booking_id uuid not null references public.bookings(id) on delete cascade, status public.booking_status not null, actor_id uuid references auth.users(id), note text, created_at timestamptz not null default now());
create table if not exists public.quotations (id uuid primary key default gen_random_uuid(), booking_id uuid not null references public.bookings(id) on delete cascade, total numeric(12,2) not null default 0, advance_required numeric(12,2) not null default 0, remaining numeric(12,2) not null default 0, validity_date date, terms text, notes text, status text not null default 'draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.quotation_items (id uuid primary key default gen_random_uuid(), quotation_id uuid not null references public.quotations(id) on delete cascade, description text not null, quantity numeric not null default 1, unit_price numeric(12,2) not null default 0, discount numeric(12,2) not null default 0);
create table if not exists public.payments (id uuid primary key default gen_random_uuid(), booking_id uuid not null references public.bookings(id), customer_id uuid references public.customers(id), razorpay_order_id text, razorpay_payment_id text, payment_type text not null, amount numeric(12,2) not null, status text not null default 'created', created_at timestamptz not null default now());
create index if not exists bookings_date_idx on public.bookings(event_date); create index if not exists bookings_status_idx on public.bookings(status); create index if not exists bookings_customer_idx on public.bookings(customer_id);

alter table public.profiles enable row level security; alter table public.customers enable row level security; alter table public.bookings enable row level security; alter table public.booking_status_history enable row level security; alter table public.quotations enable row level security; alter table public.payments enable row level security;
create policy "profiles own row" on public.profiles for all using (id = auth.uid()) with check (id = auth.uid());
create policy "customers own row" on public.customers for select using (profile_id = auth.uid());
create policy "bookings own rows" on public.bookings for select using (customer_id in (select id from public.customers where profile_id = auth.uid()));
create policy "history own rows" on public.booking_status_history for select using (booking_id in (select id from public.bookings where customer_id in (select id from public.customers where profile_id = auth.uid())));
create policy "quotations own rows" on public.quotations for select using (booking_id in (select id from public.bookings where customer_id in (select id from public.customers where profile_id = auth.uid())));
create policy "payments own rows" on public.payments for select using (customer_id in (select id from public.customers where profile_id = auth.uid()));